### ISSUE TITLE
Implement v2 changes based on feedback

### ISSUE THREAD

**Issue by koobs** [cosites/propertyoptions#5]
Client provided favourable feedback based on v1 skeleton, with feedback and requested changes as in #3.

- [ ] Add/Change images to land subdivision and/or australian landmarks or inspiring places. Use `pixabay.com` (or similar) for freely licensed images.

Additionally:

## Add favicon.ico

Currently 404

![Screen Shot 2023-05-08 at 4 59 12 pm](https://user-images.githubusercontent.com/1011612/236756115-95330e26-9692-4a37-a12a-b25a6d2ed6ae.png)

## Add real contact details in footer

![Screen Shot 2023-05-08 at 4 57 46 pm](https://user-images.githubusercontent.com/1011612/236755864-07a54711-b92e-41f8-a4aa-beeecd0b55bd.png)

## Update <title> 

 * remove Lorem Ipsum
 * Add `Property Options Australia`

![Screen Shot 2023-05-08 at 5 00 19 pm](https://user-images.githubusercontent.com/1011612/236756554-0edb6a42-c584-44ee-9ab5-cfc767c42f98.png)

![Screen Shot 2023-05-08 at 4 59 48 pm](https://user-images.githubusercontent.com/1011612/236756548-5767c4a7-626d-4ade-b881-6cb11f463218.png)

## Update, simplify and tweak body text 

 * details to come
 
## Break up large body text 

Add 2 or 3 images to break up large single chunk of body text at appropriate spots.

There are 15 images in Dropbox to select from. Choose at least one "Sydney" image, one "property design" image and one "land subdivision/plan image"

Might be worth trying a zigzag pattern, like

`
paragraph, image
image, paragraph
paragraph, image
image, paragraph
`

## Remove About and Services links

 * from header
 * remove quicklinks in footer entirely (it also doesn't work well at smaller devices sizes currently)
 
![Screen Shot 2023-05-08 at 5 04 37 pm](https://user-images.githubusercontent.com/1011612/236757303-d0345486-660d-4cad-afc4-5e75ae5d0c63.png)

![Screen Shot 2023-05-08 at 5 04 07 pm](https://user-images.githubusercontent.com/1011612/236757294-1c1bbd7e-a791-42de-8c8e-41d8c1ba8e36.png)

## Replace placeholder with company name in copyright

![Screen Shot 2023-05-08 at 5 06 05 pm](https://user-images.githubusercontent.com/1011612/236757592-bdf44f70-687f-478f-9461-24bfa20b2066.png)

## Move "find your dream home ..." 

Move top of blue footer section to top under main header ...

![Screen Shot 2023-05-08 at 5 08 54 pm](https://user-images.githubusercontent.com/1011612/236759016-c2e91ec4-7a37-4c15-8ba7-54d8739be25f.png)
![Screen Shot 2023-05-08 at 5 07 33 pm](https://user-images.githubusercontent.com/1011612/236759031-8449bdc2-8cf4-4e22-ae05-68b991bd0cca.png)

## Change "contact us" text

to `Contact us at Property Options Australia` (seo)

![Screen Shot 2023-05-08 at 5 15 54 pm](https://user-images.githubusercontent.com/1011612/236759902-c3e0461d-31e3-480f-aba1-58cc68df5453.png)

## Move horizontal rule and copyright

move out of blue block, and down onto page background (darker blue) at the bottom

![Screen Shot 2023-05-08 at 5 19 14 pm](https://user-images.githubusercontent.com/1011612/236760416-c130c00b-6dcb-4e3f-9a93-b0c664d12ebb.png)

- [ ] ...

**Comment by koobs** [comment]
I've added 15 freely licensed images in Dropbox to select from for the "break up large body of text" item in this issues main description

**Comment by kfv** [comment]
@koobs: Just pushed. Take a look and close the issue if it looks good to you ATM.

**Comment by koobs** [comment]
Look good. Final v3 tweaks to come
